### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by mweiss-focus** [quentinhardy/jndiat#1]
I think that you forgot to upload the source code. The git repository is empty.

**Comment by ramnarayanp** [comment]
See here for source code - https://github.com/quentinhardy/jndiat/releases

**Comment by mweiss-focus** [comment]
I got an email from someone named Ramnarayan that pointed me to the releases page. This has a .zip file that only has a LICENSE and README.md file. I'm not sure if that email is something that is automated or not.

**Comment by quentinhardy** [comment]
Source code: [https://github.com/quentinhardy/jndiat/tree/master/source](https://github.com/quentinhardy/jndiat/tree/master/source)

Standalone Jar: [https://github.com/quentinhardy/jndiat/releases/download/0.01/jndiat_v0.01.jar](https://github.com/quentinhardy/jndiat/releases/download/0.01/jndiat_v0.01.jar)

**Comment by mweiss-focus** [comment]
thanks!
